services:
  - type: web
    name: myai
    runtime: python
    repo: https://github.com/vinamrag-code/MyAI
    branch: ai-search
    build:
      pythonVersion: 3.11
      commands:
        - pip install --upgrade pip
        - pip install wheel
        - pip install -r requirements.txt
    start: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11